CREATE DATABASE posDB;
USE posDB;
CREATE TABLE tblUser
(
id INT PRIMARY KEY IDENTITY(1, 1),
userName VARCHAR(50) NOT NULL UNIQUE,
gender VARCHAR(6) NOT NULL,
password VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
status BIT NOT NULL,
createAt DATETIME NOT NULL,
createBy INT NOT NULL,
updateAt DATETIME NULL,
updateBy INT NULL
);
CREATE TABLE tblRole
(
id INT PRIMARY KEY IDENTITY(1, 1),
name VARCHAR(50) NOT NULL UNIQUE,
status BIT NOT NULL,
createAt DATETIME NOT NULL,
createBy INT NOT NULL,
updateAt DATETIME NULL,
updateBy INT NULL,
);
CREATE TABLE tblUserRole
(
id INT PRIMARY KEY IDENTITY(1, 1),
userId INT NOT NULL,
roleId INT NOT NULL,
createAt DATETIME NOT NULL,
createBy INT NOT NULL,
updateAt DATETIME NULL,
updateBy INT NULL
);
CREATE TABLE tblCategory
(
id INT PRIMARY KEY IDENTITY(1, 1),
categoryName VARCHAR(50) NOT NULL UNIQUE,
status BIT NOT NULL,
createAt DATETIME NOT NULL,
createBy INT NOT NULL,
updateAt DATETIME NULL,
updateBy INT NULL
);
CREATE TABLE tblProduct 
(
id INT PRIMARY KEY IDENTITY(1, 1),
productName VARCHAR(50) NOT NULL UNIQUE,
barcode BIGINT NOT NULL UNIQUE,
sellPrice DECIMAL(8, 2) NOT NULL,
qtyInStock INT NULL,
photo VARCHAR(255) NULL,
categoryId INT NOT NULL,
createAt DATETIME NOT NULL,
createBy INT FOREIGN KEY REFERENCES tblUser(id),
updateAt DATETIME NULL,
updateBy INT FOREIGN KEY REFERENCES tblUser(id) NULL
);
CREATE TABLE tblSupplier
(
id INT PRIMARY KEY IDENTITY(1, 1),
name VARCHAR(50) NOT NULL UNIQUE,
tel INT NOT NULL,
address VARCHAR(50) NOT NULL,
createAt DATETIME NOT NULL,
createBy INT NOT NULL,
updateAt DATETIME NULL,
updateBy INT NULL
);
CREATE TABLE tblAddStock 
(
id INT PRIMARY KEY IDENTITY(1, 1),
supplierId INT NOT NULL,
productId INT NOT NULL,
qty INT NOT NULL,
cost DECIMAL(8, 2) NOT NULL,
total DECIMAL(8, 2) NOT NULL,
createAt DATETIME NOT NULL,
createBy INT NOT NULL,
updateAt DATETIME NULL,
updateBy INT NULL
);
CREATE TABLE tblSale
(
id INT PRIMARY KEY IDENTITY(1, 1),
customerId INT NULL,
saleDate DATETIME NOT NULL,
userId INT NOT NULL,
totalAmount DECIMAL(8, 2) NOT NULL
);
CREATE TABLE tblSaleDetail
(
id INT PRIMARY KEY IDENTITY(1, 1),
saleId INT NOT NULL,
productId INT NOT NULL,
qty INT NOT NULL,
price DECIMAL(8, 2) NOT NULL,
total DECIMAL(8, 2) NOT NULL
);
CREATE TABLE tblCustomer
(
id INT PRIMARY KEY IDENTITY(1, 1),
name VARCHAR(50) NOT NULL,
gender VARCHAR(6) NOT NULL,
tel INT NOT NULL,
address VARCHAR(50) NOT NULL,
createAt DATETIME NOT NULL,
createBy INT NOT NULL,
updateAt DATETIME NULL,
updateBy INT NULL
);
